### ISSUE TITLE
Could not resolve com.appboy:android-sdk-jar:1.6.+

### ISSUE THREAD

**Issue by mg6maciej** [Appboy/appboy-android-sdk#32]
Today, when I opened IDE, this compilation error showed up. It was working properly 2 days ago and I made no changes since then.

    Error:A problem occurred configuring root project 'MyProjectName'.
    > Could not resolve all dependencies for configuration ':_stagingDebugCompile'.
       > Could not resolve com.appboy:android-sdk-jar:1.6.+.
         Required by:
             :MyProjectName:unspecified > com.appboy:android-sdk-ui:1.6.0
          > Failed to list versions for com.appboy:android-sdk-jar.
             > Unable to load Maven meta-data from http://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-jar/maven-metadata.xml.
                > org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 35; The entity "middot" was referenced, but not declared.

**Comment by briancaw** [comment]
Hi @mg6maciej

 I can't reproduce this; also, we haven't changed the public repo in over a month (see https://github.com/Appboy/appboy-android-sdk/commits/gh-pages).  

It sounds like there might have been a github service blip, temporary loss of internet, or some other transient error.  Can you try again and see if you can reproduce this?

**Comment by briancaw** [comment]
Also @mg6maciej, if this problem persists - if you could provide your gradle version as well as your IDE and version, that would be helpful for debugging.

**Comment by carlbenson** [comment]
I can confirm that this is still an issue. There seems to be a missing file. When running gradle with debug flag, I see this
<code>org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.MetaDataParseException: Could not parse POM http://appboy.github.io/appboy-android-sdk/sdk/com/android/support/support-v4/21.0.0/support-v4-21.0.0.pom
</code>
and requesting this file using wget I get an HTML page from GitHub saying this file does not exist.

**Comment by MichaelEvans** [comment]
Looks like there's some broken configuration:

http://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-jar/maven-metadata.xml

Seems to be missing. Maybe Github changed something on their end?

**Comment by briancaw** [comment]
I think that the missing file error might be a red herring - or it's being caused by a change in gradle suddenly requiring it, not by the file disappearing.  i.e.  It never existed in our public maven repo.

@MichaelEvans Are you having the same problem as well?  If so, can you tell me what version of gradle you're using?

**Comment by briancaw** [comment]
Hi All

I've just added maven-metadata.xml files to our sdk repos.  Being that we're still trying to reproduce this error, if someone could let us know if this fixes things it would be a big help.

**Comment by jonathan-caryl** [comment]
@briancaw I work with @MichaelEvans, and I was seeing this issue. It seems to be fixed for me now.

**Comment by briancaw** [comment]
Thanks for the update @jonathan-caryl .  @mg6maciej Please let me know if this solves the issue for you as well.

@carlbenson I'm not sure that you're having the same issue.  The error you've posted seems to be related to not having the support library.  Can you install the support library (Extras -> Android Support Library) via Android Studio or add 

compile 'com.android.support:support-v4:21.+' 

to your dependencies and let me know if the problem persists.

**Comment by mg6maciej** [comment]
I have removed the library for now. Waiting for re-evaluation of its usefulness from the business side.

**Comment by yishai-glide** [comment]
@mg6maciej  how is that helpful in fixing this issue?!

**Comment by mg6maciej** [comment]
@yishai-glide I replied to project maintainer, that I won't be able to verify it. You may just ignore my comment.

**Comment by billmag** [comment]
Thanks for the engagement on this issue everyone. We're still actively investigating and would appreciate any further reports (positive or negative). If it ends up being a repeating transient Github Pages issue, we'll also look into permanently moving our maven file hosting to somewhere else.

**Comment by pascallaniel** [comment]
I was having the exact same problem this morning. It is now working properly.

Thank you!

**Comment by carlbenson** [comment]
@briancaw https://github.com/Appboy/appboy-android-sdk/commit/0985f68e2ff09db23b16f2f20787f1307bcdc1cc fixed my issue but there is still a lot of noise when building.

**Comment by briancaw** [comment]
Thanks for all of the information everyone; it appears all of the build issues are fixed.  We'll work on getting the build noise fixed for the next release.

**Comment by BrantApps** [comment]
Still an issue AppBoy? Attempting to integrate with android-sdk-ui at v1.6.2 and receiving this same error message. Using Android Studio 1.1 and android-gradle tooling at v1.1.0.

    Failed to resolve com.appboy:android-sdk-ui:1.6.2

**Comment by briancaw** [comment]
Hi @BrantApps 

We haven't modified that release since this issue was resolved and haven't heard any reports of broken behavior since closing this.

I've double checked this functionality and things appear to be working, so I'd advise what I originally did on this thread before it became clear there was an issue:

"It sounds like there might have been a github service blip, temporary loss of internet, or some other transient error. Can you try again and see if you can reproduce this?"

Please let me know if you continue to have issues and we'll debug further.
